export const DATA_PROFILE_UPDATE_SUCCESS = "DATA_PROFILE_UPDATE_SUCCESS"
export const DATA_PROFILE_UPDATE_FAILURE = "DATA_PROFILE_UPDATE_FAILURE"
export const DATA_PROFILE_SUCCESS = "DATA_PROFILE_SUCCESS"
export const DATA_PROFILE_FAILURE = "DATA_IMAGE_FAILURE"
export const DATA_PROFILE_CLEAR = "DATA_PROFILE_CLEAR"

export const DATA_LAST_HEALTH_SUCCESS = "DATA_LAST_HEALTH_SUCCESS"
export const DATA_LAST_HEALTH_FAILURE = "DATA_LAST_HEALTH_FAILURE"

export const DATA_IMAGE_SUCCESS = "DATA_IMAGE_SUCCESS"
export const DATA_IMAGE_FAILURE = "DATA_IMAGE_FAILURE"

export const DATA_ACHIEVEMENTS_SUCCESS = "DATA_ACHIEVEMENTS_SUCCESS"
export const DATA_ACHIEVEMENTS_FAILURE = "DATA_ACHIEVEMENTS_FAILURE"